# TARGET_PACK: c=Charizard, m=Mewtwo, p=Pikachu
TARGET_PACK: "c"
# refer to res/card
TARGET_CARD_LIST:
  - "cPK_20_000040_00_FUSHIGIBANAex_SR"
  - "cPK_20_000230_00_NASSYex_SR"
  - "cPK_20_000360_00_LIZARDONex_SR"
  - "cPK_20_000410_00_WINDIEex_SR"
  - "cPK_20_000470_00_FIREex_SR"
  - "cPK_20_000560_00_KAMEXex_SR"
  - "cPK_20_000760_00_STARMIEex_SR"
  - "cPK_20_000840_00_FREEZERex_SR"
  - "cPK_20_000960_00_PIKACHUex_SR"
  - "cPK_20_001040_00_THUNDERex_SR"
  - "cPK_20_001230_00_GANGARex_SR"
  - "cPK_20_001290_00_MEWTWOex_SR"
  - "cPK_20_001460_00_KAIRIKYex_SR"
  - "cPK_20_001530_00_GARAGARAex_SR"
  - "cPK_20_001950_00_PUKURINex_SR"
  - "cTR_20_000110_00_ERIKA_SR"
  - "cTR_20_000120_00_KASUMI_SR"
  - "cTR_20_000130_00_KATSURA_SR"
  - "cTR_20_000140_00_KYOU_SR"
  - "cTR_20_000150_00_SAKAKI_SR"
  - "cTR_20_000160_00_TAKESHI_SR"
  - "cTR_20_000170_00_NATSUME_SR"
  - "cTR_20_000180_00_MATISSE_SR"
  - "cPK_20_000470_01_FIREex_SAR"
  - "cPK_20_000840_01_FREEZERex_SAR"
  - "cPK_20_001040_01_THUNDERex_SAR"
  - "cPK_20_001230_01_GANGARex_SAR"
  - "cPK_20_001460_01_KAIRIKYex_SAR"
  - "cPK_20_001950_01_PUKURINex_SAR"

# user name in game, add {IDX} for 3 digi index, reset after 1000
USERNAME: "abc{IDX}"

LD_EMU_NAME: "PTCGP-Gacha-00"
LDPLAYER_PATH: "D:\\LDPlayer\\LDPlayer9"
