# TARGET_PACK: charizard, mewtwo, pikachu, mew
TARGET_PACK: "mew"

# refer to res\card
TARGET_CARD_LIST:
  - "cTR_20_000110_00_ERIKA_SR"
  - "cTR_20_000120_00_KASUMI_SR"
  - "cTR_20_000130_00_KATSURA_SR"
  - "cTR_20_000140_00_KYOU_SR"
  - "cTR_20_000150_00_SAKAKI_SR"
  - "cTR_20_000160_00_TAKESHI_SR"
  - "cTR_20_000170_00_NATSUME_SR"
  - "cTR_20_000180_00_MATISSE_SR"
  - "cTR_20_000210_00_GREEN_SR"
  - "cTR_20_000220_00_KAKEDASHICHOSAIN_SR"
  - "cTR_20_000230_00_LEAF_SR"
  - "cPK_20_002170_00_CELEBIex_SR"
  - "cPK_20_002450_00_MEWex_SR"

STOP_AT_RARE_PACK: true

# user name in game, add {IDX} for 3 digi index, reset after 1000
USERNAME: "Gachapon{IDX}"

LD_EMU_NAME: "PTCGP-Gacha-00"

# LDPLAYER_PATH: write "\" as "\\"
LDPLAYER_PATH: "D:\\LDPlayer\\LDPlayer9"

# Telegram Token and Chat ID
TG_TOKEN: ""
TG_CHAT_ID: ""

# Enable debug mode to log, default is true
# DEBUG_MODE: false
